info:
  name: @project.name@
  version: @project.version@
management:
  endpoints:
    web:
      base-path: /application
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
  health:
    diskspace:
      threshold: 5368709120
    redis:
      enabled: false
spring:
  data:
    mongodb:
      database: bdtransaccions
      uri: mongodb+srv://user_mongo:G1TFNZUPitWXoy8z@cluster0.7dn2n.mongodb.net/bdtransaccions?retryWrites=true&w=majority
      repositories:
        type: auto
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
##mongodb://localhost:27017
##mongodb+srv://user_mongo:<password>@cluster0.7dn2n.mongodb.net/<dbname>?retryWrites=true&w=majority